# Generated by Django 4.2.3 on 2023-08-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='image-default.png', upload_to='post_images/'),
        ),
    ]
