# Generated by Django 4.2.3 on 2023-08-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='media/default-image.png', upload_to='media/post_images/'),
        ),
    ]
